schema: ./src/graphql/schema.graphql
extensions:
  endpoints:
    GraphQLZero GraphQL Endpoint:
      url: https://graphqlzero.almansi.me/api
      headers:
        user-agent: JS GraphQL
      introspect: false
